### ISSUE TITLE
Missing a config file for wpa_supplicant?

### ISSUE THREAD

**Issue by jmachuca77** [emlid/pywificontrol#8]
Hi thank you very much for open sourcing this. I have been trying to get this going on an Edison, but I keep getting an error:
```
File "build/bdist.linux-i686/egg/wificontrol/utils/dbuswpasupplicant.py", line 94, in get_interface
wificontrol.utils.dbuswpasupplicant.InterfaceError: fi.w1.wpa_supplicant1.InterfaceUnknown: wpa_supplicant knows nothing about this interface.
```

is there something I am missing regarding configuration of wpa_supplicant?

**Comment by egorf** [comment]
Hi!

I'll need some more details on this. What Edison firmware are you using(I'll need a link to test). What exactly did you execute in your script?

**Comment by jmachuca77** [comment]
Thanks for the response, I get that error with any command that involves wpasupplicant. So for example:

```python
root@edison Developer $ python
Python 2.7.9 (default, Aug 13 2016, 16:41:35) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wificontrol
>>> wifi = wificontrol.WiFiControl()
>>> wifi.get_status()
('hostapd', None)
>>> wifi.start_client_mode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-i686/egg/wificontrol/wificontrol.py", line 65, in start_client_mode
  File "build/bdist.linux-i686/egg/wificontrol/wpasupplicant.py", line 86, in start
  File "build/bdist.linux-i686/egg/wificontrol/utils/dbuswpasupplicant.py", line 172, in initialize
  File "build/bdist.linux-i686/egg/wificontrol/utils/dbuswpasupplicant.py", line 94, in get_interface
wificontrol.utils.dbuswpasupplicant.InterfaceError: fi.w1.wpa_supplicant1.InterfaceUnknown: wpa_supplicant knows nothing about this interface.
>>> 
```

The image I am creating one so I can upload it for you to test on. I'll write once its uploaded somewhere.

**Comment by jmachuca77** [comment]
Here is the image I am trying this on https://www.dropbox.com/s/7uu5rxuj960kkpw/ArduPilotCompanionEdisonImage0.1.2.zip?dl=0

**Comment by egorf** [comment]
@jmachuca77 
I haven't had a chance to investigate the issue completely yet, but the rootfs is 100% full. That might just be the issue.

**Comment by jmachuca77** [comment]
Sorry! I forgot to mention, I don't know why but after flashing that happens. Please expand the file system 
```
sudo resize2fs /dev/mmcblk0p8
```

**Comment by jmachuca77** [comment]
by the way the root password is ardupilot

**Comment by egorf** [comment]
@jmachuca77 yeah, thanks.
Well, from what I can see, the problem is that your system is more debian-like. Networking.service overrides wpa_supplicant.service in the system and actually launches wpa_supplicant.

The dbus interface path and name the pywificontrol library knows are the same ones as configured in `/etc/dbus-1/system.d/wpa_supplicant.conf`. On our image the library works because there is no additional abstraction layer above hostapd and wpa_supplicant services. My guess is that you should try to rework the wpa_supplicant service to actually be fully working. Intel's image has this figured out, btw.

**Comment by egorf** [comment]
@jmachuca77 Maybe you can flash one of your edisons with a [reach image](https://docs.emlid.com/reach/common/reachview/firmware-reflashing/) to see what we have going on?

**Comment by jmachuca77** [comment]
Ok, do you know of a tutorial on setting up wpa_supplicant?

**Comment by egorf** [comment]
Well, Edison is very specific in this field. Can you try using Intel-provided recipes for wpa_supplicant and hostapd from meta-intel-edison? In case you need the exact recipes, tell me.

The trick on Edison is that the service's ExecStartPre and ExecStopPost actually reload the wi-fi kernel module with different flags, so I did not mess around with them much when building our image.

**Comment by jmachuca77** [comment]
Ok, ill try this weekend to get it to work. if you do have the exact recipe it would be a great help

**Comment by jmachuca77** [comment]
I was able to get this working, first it was a misconfiguration of the wpa_supplciant.service and hosted.service files, Also the .conf files for Both are important, I had to copy them from my Reach RTK unit. I also needed the files from reachstatus which I also had to copy from my Reach unit. And the updater (server.py) flask interface to tie it all together nicely.

**Comment by egorf** [comment]
@jmachuca77 
Awesome!
Don't hesitate to open more issues if you have more questions!

**Comment by sglza** [comment]
> I was able to get this working, first it was a misconfiguration of the wpa_supplciant.service and hosted.service files, Also the .conf files for Both are important, I had to copy them from my Reach RTK unit. I also needed the files from reachstatus which I also had to copy from my Reach unit. And the updater (server.py) flask interface to tie it all together nicely.

@jmachuca77 by any chance do you remember in more detail what were the changes that you made?  Even if you could point me in the right direction it might be enough, I am receiving the same error message `wpa_supplicant knows nothing about this interface` while working with the `dbus-python` library. I also happen to be using a Raspberry Pi, which has a debian-like system and as egorf mentions might be part of the issue.

**Comment by jmachuca77** [comment]
Sorry I don't remember... but I do know I had this working on a pi at some point too.
